<div id="header">
    <div class="container">
        <span id="logo"><a href="/" title="Home"><img src="<?php echo $basePath ?>/themes/dtk/images/logo.png" alt="Dojo Toolkit" /></a></span>
        <ul id="navigation">
			<li class="home"><a href="/"><span class="homeIcon"></span></a></li>
			<li class="download"><a href="/download/">Download</a></li>
			<li class="features"><a href="/features/">Features</a></li>
        	<li class="docs"><a href="/documentation">Documentation</a></li>
        	<li class="community"><a href="/community">Community</a></li>
        	<li class="blog"><a href="/blog">Blog</a></li>
        </ul>
    </div>
</div>
